accounts:
  - name: chora-1-validator
    coins: ["500chora", "500000000stake"]
  - name: chora-1-user
    coins: ["500chora"]
validator:
  name: chora-1-validator
  staked: "100000000stake"
faucet:
  name: chora-1-user
  coins:
    - "5chora"
genesis:
  chain_id: "chora-1"
init:
  home: ".chora-1"